### ISSUE TITLE
Updating a serializer won't work without the foreign key

### ISSUE THREAD

**Issue by lesreaper** [yezyilomo/django-restql#188] opened 2020-10-12 20:58 UTC
Awesome library, love what you're doing here.

My only challenge is updating parent model without adding the child key. So, if I just want to PATCH one field on the `Room` model below, like the `name`, I don't want to have to add the `castle` id as well to the main body call. Here's the code

`serializers.py`
```
class CastleSerializer(DynamicFieldsMixin, serializers.ModelSerializer):
    class Meta:
        model = Castle
        fields = '__all__'

class RoomSerializer(DynamicFieldsMixin, NestedModelSerializer):
    castle = NestedField(CastleSerializer, accept_pk=True)

    class Meta:
        model = Room
        fields = ('id', 'name', 'castle')
```

I would expect to be able to POST or PATCH an update method without having to add the nested `castle` id and have it just validate and work.

API call: `PATCH /api/v1/rooms-update/`
```
[
  {
    "id": 1,
    "name": "Throne Room Changed Text",
  }
]
```
should return
```
[
  {
    "id": 1,
    "name": "Throne Room Changed Text",
    "castle": {
        "id": 1,
        "name": "Daventry Castle"
    }
  }
]

```
It seems none of this is currently working, but when I add the `castle` primary key, it works just fine. I could change the
```
castle = NestedField(CastleSerializer, accept_pk=True)
```
to
```
castle = NestedField(CastleSerializer, required=False, allow_null=True)
```
but that would update the castle field to `null`, when instead I want it to keep it's previous value (since it's not part of the body text).

How do I go about this?

**Comment by lesreaper** [comment] 2020-10-13 00:35
So, maybe I solved this with a hack.

In the PATCH view method for the Room, I wrote the following:

`views_room.py`
```
@api_view(['PATCH'])
def roomsUpdate(request):
  room_data = Room.objects.get(id=request.data.id)
  if not "castle" in request.data:
      try:
          castle = Castle.objects.get(pk=room_data.castle.id)
          request.data["castle"] = castle.id
      except Exception as e:
          print("[ERROR]: No castle to begin with")

  serializer = RoomSerializer(instance=room_data, data=request.data)

  if serializer.is_valid():
      serializer.save()

  return Response(serializer.data)
```
If there'a a better way, I'm definitely open to it!

**Comment by yezyilomo** [comment] 2020-10-16 18:23
> but that would update the castle field to `null`, when instead I want it to keep it's previous value (since it's not part of the body text).
> 
> How do I go about this?

I don't think it would update the castle field to `null` when you use `castle = NestedField(CastleSerializer, required=False, allow_null=True)`.
Check https://django-restql.yezyilomo.com/mutating_data/#using-dynamicfieldsmixin-and-nestedfield-together for more details about this behaviour.

**Comment by resurrexi** [comment] 2020-11-16 06:26
You can use `castle = NestedField(CastleSerializer, accept_pk=True, required=False, allow_null=True)`. That way, when you do need to pass a pk to this attribute on a POST/PATCH, it updates the `castle` attribute, and preserves the old value if you don't update this attribute at all.

**Comment by dnievas04** [comment] 2021-08-04 21:40
Hi @resurrexi I am facing the same problem. I have tried your solution but I keep getting a value error. 

`ValueError: Cannot assign "<class 'rest_framework.fields.empty'>": "Room.castle" must be an instance of "Castle"`.

In my case the related object cannot be null, so the `required=False` solution is not an option for our use case.

Any idea how to solve this problem? Is it a bug? Can it be considered a problem? or an improvement to implement?
Thanks!

**Comment by yezyilomo** [comment] 2021-08-04 23:11
> Hi @resurrexi I am facing the same problem. I have tried your solution but I keep getting a value error.
> 
> `ValueError: Cannot assign "<class 'rest_framework.fields.empty'>": "Room.castle" must be an instance of "Castle"`.
> 
> In my case the related object cannot be null, so the `required=False` solution is not an option for our use case.
> 
> Any idea how to solve this problem? Is it a bug? Can it be considered a problem? or an improvement to implement?
> Thanks!

Are you using `PUT` or `PATCH`? because there’s a difference.

**Comment by dnievas04** [comment] 2021-08-05 10:58
@yezyilomo, I am using PATCH. I think for a PUT this is the expected behavior, but when using PATCH one expects to send only the fields to update. What are your thoughts on this?

**Comment by yezyilomo** [comment] 2021-08-05 11:53
> @yezyilomo, I am using PATCH. I think for a PUT this is the expected behavior, but when using PATCH one expects to send only the fields to update. What are your thoughts on this?

I haven’t succeeded to reproduce it on my side, can I see your serializer and json data which you send through PATCH request. Specifying your django-restql version would be bery helpful.

**Comment by gonzaloamadio** [comment] 2021-08-05 14:22
@yezyilomo there is a repository here where you can reproduce the bug.
In the readme, there is a section with the tests we did to reproduce.

Basically you have to patch a model with nested fields. There, if we do not send all fields, it fails.

[Repository](https://github.com/gonzaloamadio/django-nested-serializers/tree/main/restql)

**Comment by dnievas04** [comment] 2021-08-05 14:56
> @yezyilomo there is a repository here where you can reproduce the bug.
> In the readme, there is a section with the tests we did to reproduce. Also at the beginning of it there are the package versions.
> 
> Basically you have to patch a model with nested fields. There, if we do not send all fields, it fails.
> 
> [Repository](https://github.com/gonzaloamadio/django-nested-serializers/tree/main/restql)

Just to clarify, @gonzaloamadio is talking about the "Second Bug" reported in the Readme. Here is the [link](https://github.com/gonzaloamadio/django-nested-serializers/tree/main/restql#second-bug-have-to-put-full-object-for-patching)

**Comment by yezyilomo** [comment] 2021-08-05 21:54
@gonzaloamadio @dnievas04 

> @yezyilomo there is a repository here where you can reproduce the bug.
> In the readme, there is a section with the tests we did to reproduce. Also at the beginning of it there are the package versions.
> 
> Basically you have to patch a model with nested fields. There, if we do not send all fields, it fails.
> 
> [Repository](https://github.com/gonzaloamadio/django-nested-serializers/tree/main/restql)

You are actually using `NestedField` without inheriting `NestedModelSerializer` [HERE](https://github.com/gonzaloamadio/django-nested-serializers/blob/082667e7f7c025186329da9ccdc8692080c66ef4/restql/serializers.py#L15-L21), That's what causing that error.

It should be 
```py
class IngredientMixSerializer(DynamicFieldsMixin, NestedModelSerializer):

    ingredient = NestedField(IngredientSerializer, accept_pk_only=True)

    class Meta:
        model = IngredientMix
        fields = ['id', 'ingredient', 'product', 'name']
```

`IngredientMix` is a nested model because you have defined a nested field(`ingredient`) in it, so its serializer should inherit `NestedModelSerializer`.

**Comment by dnievas04** [comment] 2021-08-06 13:25
Oh! I'm sorry. You are absolutely right. It is now working as expected.

Thanks!

**Comment by yezyilomo** [comment] 2021-08-06 19:47
Am closing this because it's not a bug, Just remember to inherit from `NestedModelSerializer` if your serializer is nested and you have used `NestedField` to define at least one nested field.

**Closed** 2021-08-06 19:47 UTC
